version: 2

# Build documentation in the documentation/sphinx/ directory with Sphinx
sphinx:
  configuration: documentation/sphinx/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: documentation/sphinx/requirements.txt
    - method: pip
      path: .

# Don't build any extra formats
formats: []
