class_diagram_main.png : class_diagram_main.dot
	dot -Tpng $< -o $@

class_diagram_messaging.png : class_diagram_messaging.dot
	dot -Tpng $< -o $@

class_diagram_signalling.png : class_diagram_signalling.dot
	dot -Tpng $< -o $@

example_contexts.png : example_contexts.dot
	dot -Tpng $< -o $@
