name: QMI Python CI runner on push

on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - ACKNOWLEDGEMENTS.md
      - LICENSE.md
      - CONTRIBUTING.md
      - TESTING.md

env:
  PYLINT_MIN_SCORE: "9.00"
  COVERAGE_MIN_PERC: "90"
  COMPLEXITY_MAX_SCORE: "30"
  SOURCE_DIRS: "qmi/"

jobs:
  on_push:
    uses: ./.github/workflows/reusable-ci-workflows.yml
    with:
      python-version: "3.11"
#      repo-token: ${{ secrets.envPAT }}
