name: QMI Python CI runner on push

on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - ACKNOWLEDGEMENTS.md
      - LICENSE.md
      - CONTRIBUTING.md
      - TESTING.md

jobs:
  on_push:
    uses: ./.github/workflows/reusable-ci-workflows.yml
    with:
      python-version: "3.11"
