name: Python CI Reusable Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      ref:
        required: false
        type: string
#    secrets:
#      envPAT:
#        required: true

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y bc
          pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run pylint
        run: |
          pylint --score=yes --load-plugins=pylint.extensions.mccabe --max-complexity=$COMPLEXITY_MAX_SCORE $SOURCE_DIRS | tee pylint.log
          PYLINT_SCORE=$(tail -n 2 pylint.log | grep -o '[0-9]\{1,2\}\.[0-9]\{2\}' | head -n 1)
          echo "Pylint score: $PYLINT_SCORE"
          exit $(echo "$PYLINT_SCORE < $PYLINT_MIN_SCORE" | bc)
      - name: Upload pylint results
        uses: actions/upload-artifact@v4
        with:
          name: pylint-results
          path: pylint.log

      - name: Run mypy
        run: |
          mypy --namespace-packages $SOURCE_DIRS | tee mypy.log
          if [ -n "$(tail -n 1 mypy.log | grep -e '^Succes')" ]; then RESULT="pass"; else RESULT="fail"; fi
          echo "Mypy result: $RESULT"
          exit $([[ "$RESULT" == "pass" ]] && echo 0 || echo 1)
      - name: Upload mypy results
        uses: actions/upload-artifact@v4
        with:
          name: mypy-results
          path: mypy.log

      - name: Run coverage
        run: |
          coverage run --branch --source=$SOURCE_DIRS -m unittest discover --start-directory=tests --pattern="test_*.py"
          coverage report --show-missing --fail-under=$COVERAGE_MIN_PERC | tee coverage.log
          COVERAGE_PERC=$(grep "TOTAL" coverage.log | grep -Eo '[0-9.]+%' | sed 's/%//')
          echo "Coverage: $COVERAGE_PERC%"
          exit $(echo "$COVERAGE_PERC < $COVERAGE_MIN_PERC" | bc)
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: coverage.log
