name: QMI Python CI full test runner

on:
  schedule:
    # Schedule for every Monday at 7am
    - cron: "0 7 * * 1"

env:
  PYLINT_MIN_SCORE: "9.00"
  COVERAGE_MIN_PERC: "90"
  COMPLEXITY_MAX_SCORE: "30"
  SOURCE_DIRS: "qmi/"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Use reusable workflow
        uses: ./.github/workflows/reusable-ci-workflows.yml
        with:
          python-version: ${{ matrix.python-version }}
          repo-token: ${{ secrets.envPAT }}

      - name: Run unit tests and generate report
        if: always()
        run: |
          pip install unittest-xml-reporting
          python -m xmlrunner --output-file testresults.xml discover --start-directory=tests --pattern="test_*.py"

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: testresults.xml
